version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bala
      MONGO_INITDB_ROOT_PASSWORD: bala123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: balasuriya
      ME_CONFIG_MONGODB_ADMINPASSWORD: balasuriya@98
      ME_CONFIG_MONGODB_URL: mongodb://bala:bala123@mongo:27017/
      ME_CONFIG_BASICAUTH: false